services:
  ss14-watchdog:
    build: .
    image: ss14-watchdog
    restart: always
    ports:
      - 8080:8080/tcp
      - 1212:1212/tcp
      - 1212:1212/udp
    volumes:
      - instances:/watchdog/instances/
      - type: bind
        source: /home/.config/ss14-watchdog/appsettings.yml
        target: /watchdog/appsettings.yml

volumes:
  instances:
